In [1]:
import autograd.numpy as np
from autograd.numpy.random import normal
import pandas as pd
import matplotlib.pyplot as plt
from autograd import grad
from scipy.stats import bernoulli
from autograd.numpy import exp, log, sqrt

np.random.seed(37)

In [13]:
def f(x):
    return log(exp(sqrt(x)))
g = grad(f)
g(10.)

0.15811388300841897

In [3]:
n = 1000
X = np.vstack((
        np.hstack((np.ones(n).reshape(n, 1), np.random.multivariate_normal([0, 0], [[1, .75],[.75, 1]], n))),
        np.hstack((np.ones(n).reshape(n, 1), np.random.multivariate_normal([1, 4], [[1, .75],[.75, 1]], n)))
    )).astype(np.float32)
y = np.hstack((np.zeros(n), np.ones(n))).astype(np.float32)
w = np.array([np.random.randn() for _ in range(X.shape[1])])

In [4]:
X.dot(w)*y

array([ 0.        ,  0.        ,  0.        , ..., -0.43725146,
        0.50606308,  0.08720334])

In [5]:
sum(X.dot(w)*y - log(1. + exp(X.dot(w)))) / float(n)

-2.0686076832102254

In [6]:
log(1. + exp(X.dot(w)))

array([ 1.43415517,  1.38180315,  2.23350809, ...,  0.49823207,
        0.97785532,  0.7376991 ])

In [7]:
# plt.figure(figsize=(10, 5))
# plt.scatter(X[:, 1], X[:, 2], c=y, alpha=0.4)

In [38]:
def loss(w, X, y):
    X_dot_w = np.dot(X, w)
    t1 = X_dot_w * y
    t2 = 1. + exp(X_dot_w)
    t2 = log(t2)
    
    return np.sum(t1 - t2) / float(len(X))

#the magic line that gives you the gradient of the loss function
loss_grad = grad(loss) 

In [39]:
loss(w, X, y)

-1.0343038416051136

In [40]:
loss_grad(w, X, y)

array([-0.1396025 ,  0.35632208,  1.0291341 ])

In [41]:
for i in range(1000):
    w = w - loss_grad(w, X, y) * 0.01
    
print('intercept + weights: {}'.format(w))

intercept + weights: [ -1.11957303  -7.13506527 -21.77958787]


In [45]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X[:, [1, 2]], y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
print(lr.coef_)

[[-1.95468066  3.84431092]]


In [47]:
print(lr.intercept_)

[-6.38431868]


# References

* http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
* https://en.wikipedia.org/wiki/Logit
* http://people.seas.harvard.edu/~dduvenaud/papers/blackbox.pdf
* keyonvafa.com/logistic-regression-bbvi/
* https://beckernick.github.io/logistic-regression-from-scratch/