In [1]:
import numpy as np

$
X_0 = \left[ {\begin{array}{ccc}
0.5403 & -0.4161\\
-0.9900 & -0.6536\\
0.2837 & 0.9602\\
\end{array} } \right]
$

$
X = \left[ {\begin{array}{ccc}
1 & 0.5403 & -0.4161\\
1 & -0.9900 & -0.6536\\
1 & 0.2837 & 0.9602\\
\end{array} } \right]
$

$
\theta_1 = \left[ {\begin{array}{ccc}
0.1 & 0.3 & 0.5\\
0.2 & 0.4 & 0.6
\end{array} } \right]
$

$
\theta_2 = \left[ {\begin{array}{ccc}
0.7 & 1.1 & 1.5\\
0.8 & 1.2 & 1.6\\
0.9 & 1.3 & 1.7\\
1.0 & 1.4 & 1.8
\end{array} } \right]
$

$
y_0 = \left[ {\begin{array}{c}
4\\
2\\
3
\end{array} } \right]
$

$
y = \left[ {\begin{array}{cccc}
0 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0
\end{array} } \right]
$

$z_2 = \theta_1 X' = 
\left[ {\begin{array}{ccc}
0.1 & 0.3 & 0.5\\
0.2 & 0.4 & 0.6
\end{array} } \right]
\left[ {\begin{array}{ccc}
1 & 1 & 1\\
0.5403 & -0.9900 & 0.2837\\
-0.4161 & -0.6536 & 0.9602
\end{array} } \right]
$

$a_2 = \sigma(z_2) =
\left[ {\begin{array}{ccc}
1 & 1 & 1\\
0.51350671 & 0.3719641 & 0.66042977\\
0.54151917 & 0.35705715 & 0.70880762
\end{array} } \right]
$

$z_3 = \theta_2 a_2 =
\left[ {\begin{array}{ccc}
0.7 & 1.1 & 1.5\\
0.8 & 1.2 & 1.6\\
0.9 & 1.3 & 1.7\\
1.0 & 1.4 & 1.8
\end{array} } \right]
\left[ {\begin{array}{ccc}
1 & 1 & 1\\
0.51350671 & 0.3719641 & 0.66042977\\
0.54151917 & 0.35705715 & 0.70880762
\end{array} } \right]
$

$
a_3 = \sigma(z_3) =
\left[ {\begin{array}{ccc}
0.88866099 & 0.83817972 & 0.92341547\\
0.90742894 & 0.86028371 & 0.93857858\\
0.92330629 & 0.87980136 & 0.95089915\\
0.93665054 & 0.8969192 & 0.96085141
\end{array} } \right]
$

$
\begin{split}
L & = \frac{1}{m} \sum -y  \log(a3) - (1.0 - y) \log(1.0 - a3)\\
  & = \frac{1}{m} \sum \left[ {\begin{array}{ccc}-0.0 & -0.0 & -0.0 & -1.0\\ -0.0 & -1.0 & -0.0 & -0.0\\ -0.0 & -0.0 & -1.0 & -0.0 \end{array} } \right] \left[ {\begin{array}{cccc}-0.12 & -0.18 & -0.08\\-0.10 & -0.15 & -0.06\\-0.08 & -0.13 & -0.05\\-0.07 & -0.11 & -0.04\end{array} } \right] - \left[ {\begin{array}{ccc}1.00 & 1.00 & 1.00 & 0.00\\1.00 & 0.00 & 1.00 & 1.00\\1.00 & 1.00 & 0.00 & 1.00\end{array} } \right] \left[ {\begin{array}{cccc}-2.20 & -1.82 & -2.57\\-2.38 & -1.97 & -2.79\\-2.57 & -2.12 & -3.01\\-2.76 & -2.27 & -3.24\end{array} } \right]\\
  & = \frac{1}{m} \sum \left[ {\begin{array}{ccc}0.07 & 0.11 & 0.04\\0.10 & 0.15 & 0.06\\0.08 & 0.13 & 0.05\end{array} } \right] \left[ {\begin{array}{ccc}-7.14 & -5.91 & -8.37\\-7.52 & -6.21 & -8.82\\-7.33 & -6.06 & -8.60\end{array} } \right]\\
  &= \frac{1}{m} \sum \left[ {\begin{array}{ccc}7.21 & 6.02 & 8.41\\7.62 & 6.36 & 8.89\\7.41 & 6.19 & 8.65\end{array} } \right]\\
  &= \frac{1}{3} 66.76\\
  &= 22.25
\end{split}
$

In [49]:
def add_bias(m, horizontal=True):
    if horizontal is True:
        num_rows = m.shape[0]
        ones = np.ones(num_rows).reshape(num_rows, 1)
        return np.hstack([ones, m])
    else:
        num_cols = m.shape[1]
        ones = np.ones(num_cols).reshape(1, num_cols)
        return np.vstack([ones, m])

def sigmoid(d):
    return 1.0 / (1.0 + np.exp(-d))

X = np.matrix([
    [0.5403, -0.4161],
    [-0.9900, -0.6536],
    [0.2837, 0.9602]
], dtype=np.float)

theta1 = np.matrix([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
], dtype=np.float)

theta2 = np.matrix([
    [0.7, 1.1, 1.5],
    [0.8, 1.2, 1.6],
    [0.9, 1.3, 1.7],
    [1.0, 1.4, 1.8]
], dtype=np.float)

y = np.matrix([
    [0, 0, 0, 1],
    [0, 1, 0, 0],
    [0, 0, 1, 0]
], dtype=np.float)

m = X.shape[0]

In [50]:
a1 = add_bias(X)
z2 = np.dot(theta1, a1.transpose())

In [51]:
z2

matrix([[ 0.05404, -0.5238 ,  0.66521],
        [ 0.16646, -0.58816,  0.8896 ]])

In [52]:
a2 = add_bias(sigmoid(z2), horizontal=False)
z3 = np.dot(theta2, a2)

print(theta2.shape)
print(a2.shape)
print(z3.shape)

(4L, 3L)
(3L, 3L)
(4L, 3L)


In [53]:
a2

matrix([[1.        , 1.        , 1.        ],
        [0.51350671, 0.3719641 , 0.66042977],
        [0.54151917, 0.35705715, 0.70880762]])

In [43]:
a3 = sigmoid(z3)

In [44]:
a3

matrix([[0.88866099, 0.83817972, 0.92341547],
        [0.90742894, 0.86028371, 0.93857858],
        [0.92330629, 0.87980136, 0.95089915],
        [0.93665054, 0.8969192 , 0.96085141]])

In [48]:
loss = (1 / float(m)) * np.sum(np.dot(-y, np.log(a3)) - np.dot(1.0 - y, np.log(1.0 - a3)))

In [46]:
loss

22.25364409037751

In [76]:
def latex_print(m, pretty=False):
    num_rows = m.shape[0]
    num_cols = m.shape[1]
    s = ''
    c = '{' + ''.join(['c' for _ in range(num_rows)]) + '}'
    s = s + '\left[ {\\begin{array}' + c
    if pretty is True:
        s = s + '\n'
    for r in range(num_rows):
        o = ' & '.join(['{:.2f}'.format(m[r, c]) for c in range(num_cols)])
        if r < num_rows - 1:
            o = o + '\\\\'
        s = s + o
        if pretty is True:
            s = s + '\n'
    s = s + '\end{array} } \\right]'
    print(s)
    
latex_print(-y)
print('>')
latex_print(np.log(a3))
print('-')
latex_print(1 - y)
print('>')
latex_print(np.log(1 - a3))

\left[ {\begin{array}{ccc}-0.00 & -0.00 & -0.00 & -1.00\\-0.00 & -1.00 & -0.00 & -0.00\\-0.00 & -0.00 & -1.00 & -0.00\end{array} } \right]
>
\left[ {\begin{array}{cccc}-0.12 & -0.18 & -0.08\\-0.10 & -0.15 & -0.06\\-0.08 & -0.13 & -0.05\\-0.07 & -0.11 & -0.04\end{array} } \right]
-
\left[ {\begin{array}{ccc}1.00 & 1.00 & 1.00 & 0.00\\1.00 & 0.00 & 1.00 & 1.00\\1.00 & 1.00 & 0.00 & 1.00\end{array} } \right]
>
\left[ {\begin{array}{cccc}-2.20 & -1.82 & -2.57\\-2.38 & -1.97 & -2.79\\-2.57 & -2.12 & -3.01\\-2.76 & -2.27 & -3.24\end{array} } \right]


In [77]:
latex_print(np.dot(-y, np.log(a3)))
print('>')
latex_print(np.dot(1.0 - y, np.log(1.0 - a3)))

\left[ {\begin{array}{ccc}0.07 & 0.11 & 0.04\\0.10 & 0.15 & 0.06\\0.08 & 0.13 & 0.05\end{array} } \right]
>
\left[ {\begin{array}{ccc}-7.14 & -5.91 & -8.37\\-7.52 & -6.21 & -8.82\\-7.33 & -6.06 & -8.60\end{array} } \right]


In [78]:
latex_print(np.dot(-y, np.log(a3)) - np.dot(1.0 - y, np.log(1.0 - a3)))

\left[ {\begin{array}{ccc}7.21 & 6.02 & 8.41\\7.62 & 6.36 & 8.89\\7.41 & 6.19 & 8.65\end{array} } \right]


In [79]:
np.sum(np.dot(-y, np.log(a3)) - np.dot(1.0 - y, np.log(1.0 - a3)))

66.76093227113253

# References

* [Under the Hood of Neural Network Forward Propagation -- The Dreaded Matrix Multiplication](https://towardsdatascience.com/under-the-hood-of-neural-network-forward-propagation-the-dreaded-matrix-multiplication-a5360b33426)